# Makefile for the base Socket class
#

CXX = g++
CXXFLAGS = -std=c++11 -c

base_socket_cpp = socket.cpp

all: $(base_socket_cpp)
	$(CXX) $(CXXFLAGS) $(base_socket_cpp) -o Socket.o

clean:
	rm -rf *.o